### ISSUE TITLE
Show More

### ISSUE THREAD

**Issue by AntonCSalvador** [Xa-el/FootyFriends#19]
### Description
In order to optimize our Firebase usage and reduce the number of document reads, it's crucial that we implement a "Show More" feature for the feed on the home page (`home/+page.svelte`). Initially, the feed should load only the first five posts, with an option for users to load additional posts if they choose to.

### Scope of Change
- **File to Modify**: `home/+page.svelte`
- **Component to Update**: Feed component where the posts are rendered.
- **Expected Behavior**: The feed should initially display only five posts with a "Show More" button at the bottom. Clicking this button should load additional posts in increments determined by our FIrebase setup.

### Implementation Details
- Modify the current query to Firebase to limit the initial fetch to 5 posts.
- Implement a "Show More" button that, when clicked, fetches the next set of posts from Firebase.
- Ensure that clicking "Show More" appends the new posts to the existing list without reloading the entire feed.
- Maintain the user's scroll position when new posts are loaded to provide a seamless experience.

### Rationale
Implementing this feature will:
- Reduce the initial load on Firebase, decreasing the number of reads and potentially lowering costs.
- Improve the initial load time for users, enhancing the user experience by not making them wait for a large number of posts to load.
- Allow users more control over how much data they want to load and view at a time.

### Considerations
- We need to carefully manage state to ensure that subsequent "Show More" actions fetch the correct posts without duplication.
- Pagination or cursor-based fetching might be required to efficiently handle data retrieval from Firebase.
- Ensure that the implementation does not interfere with other interactive elements on the feed.

### Suggested Steps for Implementation
1. Update the Firebase query in the `home/+page.svelte` to include pagination logic.
2. Add a "Show More" button below the initial posts.
3. Implement the functionality to fetch additional posts when the "Show More" button is clicked.
4. Adjust the frontend to handle appending new posts to the existing list without reloading the entire component (shouldnt be that bad)

### Conclusion
Adding a "Show More" feature will not only optimize our Firebase usage but also enhance user experience by reducing wait times and providing more control over data usage. This is an essential update that aligns with our goals of improving performance and cost-efficiency.

**Comment by AntonCSalvador** [comment]
this is on home directory

**Comment by KalebE36** [comment]
Completed!
