### ISSUE TITLE
Active page status

### ISSUE THREAD

**Issue by Xa-el** [Xa-el/FootyFriends#20]
Like in the Figma, we need to have whatever page I am on be like its hovering

**Comment by Xa-el** [comment]
I got this!

**Comment by Xa-el** [comment]
I DIDNT TYPE THAT HELP!!!

**Comment by AntonCSalvador** [comment]
Like as if you were hovering on the button when you are on the page

**Comment by Xa-el** [comment]
Easy LGTM
