### ISSUE TITLE
Profile Pictures 

### ISSUE THREAD

**Issue by KalebE36** [Xa-el/FootyFriends#6]
Need to add the ability to add profile pictures upon registration. 

- Possible Image Links
- File Upload

**Comment by AntonCSalvador** [comment]
Look into Amazon S3 Buckets for this

**Comment by AntonCSalvador** [comment]
Just added check for valid image links

**Comment by AntonCSalvador** [comment]
> Look into Amazon S3 Buckets for this

I take this back, we should use Firebase storage or something else
