### ISSUE TITLE
Firebase DB setup

### ISSUE THREAD

**Issue by KalebE36** [Xa-el/FootyFriends#7]
Need to figure out how we are going to structure the firebase db for cities. 

We need to consider how we are going to structure events / messages.

Current Ideas:

- Gainesville->Chatrooms->Chatrooms A-Z->Messages P Chatroom
- Gainesville->Events->TypeOfEvent->All Events P Type->Events

**Comment by AntonCSalvador** [comment]
Good First Issue!
